Upgrade to node 16 and npm 8

diff --git a/azure/azure-release-template.yml b/azure/azure-release-template.yml
--- a/azure/azure-release-template.yml
+++ b/azure/azure-release-template.yml
@@ -45,6 +45,10 @@ extends:
         inputs:
           dockerVersion: 17.09.0-ce
           releaseType: stable
+      - task: NodeTool@0
+        displayName: Use Node v16.x
+        inputs:
+          versionSpec: '16.x'
         condition: and(succeeded(), eq(variables['run_smoke_tests'], 'true'))
       - task: DownloadSecureFile@1
         displayName: 'Download int signing cert'
@@ -69,6 +73,35 @@ extends:
 
           APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
           export APIGEE_ENVIRONMENT
+
+          # Poll deploying API until our deployed version matches the release version
+          if [ "$APIGEE_ENVIRONMENT" != "prod" ]; then
+              envPrefix="$APIGEE_ENVIRONMENT."
+          fi;
+          url="https://${envPrefix}api.service.nhs.uk/$SERVICE_BASE_PATH/_status"
+          interval_in_seconds=5
+          releaseCommit="$(Build.SourceVersion)"
+          printf "\nPolling %s every %s seconds, until commit is: %s\n" "$url" "$interval_in_seconds" "$releaseCommit"
+          attempts=0
+          success=0
+          until [ $attempts -eq 60 ]
+          do
+          responseData=$(curl -H "apiKey: $(status-endpoint-api-key)" "$url" -s)
+          deployedCommit=$(echo "$responseData" | jq -r ".commitId")
+          dependenciesUp=$(echo "$responseData" | jq -r ".status")
+          if [ "$deployedCommit" == "$releaseCommit" ] && [ "$dependenciesUp" == "pass" ]; then
+              success=1
+              break;
+          fi;
+          ((attempts=attempts+1))
+          sleep $interval_in_seconds;
+          done
+
+          if [ $success == 0 ]
+          then
+              echo "Smoke tests failed, API was not ready in time"
+              exit 255
+          fi
 
           if [[ $SERVICE_ARTIFACT_NAME == v* ]]; then
               PACT_VERSION=$STAGE_NAME
@@ -142,35 +175,6 @@ extends:
           make create-pacts > /dev/null
           chmod +x ./broker/publish.ts
           make publish-pacts > /dev/null
-
-          # Poll deploying API until our deployed version matches the release version
-          if [ "$APIGEE_ENVIRONMENT" != "prod" ]; then
-              envPrefix="$APIGEE_ENVIRONMENT."
-          fi;
-          url="https://${envPrefix}api.service.nhs.uk/$SERVICE_BASE_PATH/_status"
-          interval_in_seconds=5
-          releaseCommit="$(Build.SourceVersion)"
-          printf "\nPolling %s every %s seconds, until commit is: %s\n" "$url" "$interval_in_seconds" "$releaseCommit"
-          attempts=0
-          success=0
-          until [ $attempts -eq 60 ]
-          do
-          responseData=$(curl -H "apiKey: $(status-endpoint-api-key)" "$url" -s)
-          deployedCommit=$(echo "$responseData" | jq -r ".commitId")
-          dependenciesUp=$(echo "$responseData" | jq -r ".status")
-          if [ "$deployedCommit" == "$releaseCommit" ] && [ "$dependenciesUp" == "pass" ]; then
-              success=1
-              break;
-          fi;
-          ((attempts=attempts+1))
-          sleep $interval_in_seconds;
-          done
-
-          if [ $success == 0 ]
-          then
-              echo "Smoke tests failed, API was not ready in time"
-              exit 255
-          fi
 
           # Verify
           chmod +x ./broker/verify.ts
