pass env variables around

diff --git a/azure/azure-release-template.yml b/azure/azure-release-template.yml
--- a/azure/azure-release-template.yml
+++ b/azure/azure-release-template.yml
@@ -78,54 +78,15 @@ extends:
           #!/bin/bash
 
           set -euo pipefail
-
-          cd $(Pipeline.Workspace)/s/
-
-          SERVICE_ARTIFACT_NAME=$(SERVICE_ARTIFACT_NAME)
-          export SERVICE_ARTIFACT_NAME
-
-          SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
-          export SERVICE_BASE_PATH
-
-          APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
-          export APIGEE_ENVIRONMENT
-
-          # Poll deploying API until our deployed version matches the release version
-          if [ "$APIGEE_ENVIRONMENT" != "prod" ]; then
-              envPrefix="$APIGEE_ENVIRONMENT."
-          fi;
-          url="https://${envPrefix}api.service.nhs.uk/$SERVICE_BASE_PATH/_status"
-          interval_in_seconds=5
-          releaseCommit="$(Build.SourceVersion)"
-          printf "\nPolling %s every %s seconds, until commit is: %s\n" "$url" "$interval_in_seconds" "$releaseCommit"
-          attempts=0
-          success=0
-          until [ $attempts -eq 60 ]
-          do
-          echo "attempt: ${attempts}"
-          responseData=$(curl -H "apiKey: $(status-endpoint-api-key)" "$url" -s)
-          deployedCommit=$(echo "$responseData" | jq -r ".commitId" || echo "not_found")
-          dependenciesUp=$(echo "$responseData" | jq -r ".status" || echo "not_found")
-          if [ "$deployedCommit" == "$releaseCommit" ] && [ "$dependenciesUp" == "pass" ]; then
-              success=1
-              break;
-          fi;
-          ((attempts=attempts+1))
-          echo "sleeping ${interval_in_seconds} seconds"
-          sleep $interval_in_seconds;
-          done
-
-          if [ $success == 0 ]
-          then
-              echo "Smoke tests failed, API was not ready in time"
-              exit 255
-          fi
-        displayName: Wait for API deploy
-        condition: and(succeeded(), eq(variables['run_smoke_tests'], 'true'))
-      - bash: |
-          #!/bin/bash
-
-          set -euo pipefail
+          export SERVICE_ARTIFACT_NAME=$(SERVICE_ARTIFACT_NAME)
+          export SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
+          export APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
+          export PACT_BROKER_URL=$(PACT_BROKER_URL)
+          export PACT_BROKER_BASIC_AUTH_USERNAME=$(PACT_BROKER_BASIC_AUTH_USERNAME)
+          export PACT_BROKER_BASIC_AUTH_PASSWORD=$(PACT_BROKER_BASIC_AUTH_PASSWORD)
+          export PACT_BROKER_NEXT_URL=$(PACT_BROKER_NEXT_URL)
+          export PACT_BROKER_NEXT_TOKEN=$(PACT_BROKER_NEXT_TOKEN)
+          export PACT_PROVIDER_URL=https://$APIGEE_ENVIRONMENT.api.service.nhs.uk/$SERVICE_BASE_PATH
 
           if [[ $SERVICE_ARTIFACT_NAME == v* ]]; then
               PACT_VERSION=$STAGE_NAME
@@ -134,22 +95,6 @@ extends:
               export PACT_VERSION="$SERVICE_BASE_PATH"
           fi
 
-          PACT_BROKER_URL=$(PACT_BROKER_URL)
-          export PACT_BROKER_URL
-
-          PACT_BROKER_BASIC_AUTH_USERNAME=$(PACT_BROKER_BASIC_AUTH_USERNAME)
-          export PACT_BROKER_BASIC_AUTH_USERNAME
-
-          PACT_BROKER_BASIC_AUTH_PASSWORD=$(PACT_BROKER_BASIC_AUTH_PASSWORD)
-          export PACT_BROKER_BASIC_AUTH_PASSWORD
-
-          PACT_BROKER_NEXT_URL=$(PACT_BROKER_NEXT_URL)
-          export PACT_BROKER_NEXT_URL
-
-          PACT_BROKER_NEXT_TOKEN=$(PACT_BROKER_NEXT_TOKEN)
-          export PACT_BROKER_NEXT_TOKEN
-
-          export PACT_PROVIDER_URL=https://$APIGEE_ENVIRONMENT.api.service.nhs.uk/$SERVICE_BASE_PATH
 
           # Install dependencies for Pact tests
           echo "Installing npm packages..."
@@ -193,12 +138,162 @@ extends:
                     exit 1
               fi
           fi
+          echo "##vso[task.setvariable variable=PACT_VERSION;isOutput=true]$PACT_VERSION"
+          echo "##vso[task.setvariable variable=PACT_PROVIDER_URL;isOutput=true]$PACT_PROVIDER_URL"
+          echo "##vso[task.setvariable variable=PACT_CONSUMER;isOutput=true]$PACT_CONSUMER"
+          echo "##vso[task.setvariable variable=PACT_PROVIDER;isOutput=true]$PACT_PROVIDER"
+          echo "##vso[task.setvariable variable=SIGNING_PRIVATE_KEY_PATH;isOutput=true]$SIGNING_PRIVATE_KEY_PATH"
+          echo "##vso[task.setvariable variable=SIGNING_CERT_PATH;isOutput=true]$SIGNING_CERT_PATH"
+          echo "##vso[task.setvariable variable=API_CLIENT_ID;isOutput=true]$API_CLIENT_ID"
+          echo "##vso[task.setvariable variable=API_CLIENT_SECRET;isOutput=true]$API_CLIENT_SECRET"
+          echo "##vso[task.setvariable variable=APIGEE_ACCESS_TOKEN;isOutput=true]$APIGEE_ACCESS_TOKEN"
         displayName: Set PACT variables
+        name: setPactVariables
         condition: and(succeeded(), eq(variables['run_smoke_tests'], 'true'))
       - bash: |
           #!/bin/bash
 
           set -euo pipefail
+
+          export SERVICE_ARTIFACT_NAME=$(SERVICE_ARTIFACT_NAME)
+          export SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
+          export APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
+          export PACT_BROKER_URL=$(PACT_BROKER_URL)
+          export PACT_BROKER_BASIC_AUTH_USERNAME=$(PACT_BROKER_BASIC_AUTH_USERNAME)
+          export PACT_BROKER_BASIC_AUTH_PASSWORD=$(PACT_BROKER_BASIC_AUTH_PASSWORD)
+          export PACT_BROKER_NEXT_URL=$(PACT_BROKER_NEXT_URL)
+          export PACT_BROKER_NEXT_TOKEN=$(PACT_BROKER_NEXT_TOKEN)
+          export PACT_VERSION=$(PACT_VERSION)
+          export PACT_PROVIDER_URL=$(PACT_PROVIDER_URL)
+          export PACT_CONSUMER=$(PACT_CONSUMER)
+          export PACT_PROVIDER=$(PACT_PROVIDER)
+          export SIGNING_PRIVATE_KEY_PATH=$(SIGNING_PRIVATE_KEY_PATH)
+          export SIGNING_CERT_PATH=$(SIGNING_CERT_PATH)
+          export API_CLIENT_ID=$(API_CLIENT_ID)
+          export API_CLIENT_SECRET=$(API_CLIENT_SECRET)
+          export APIGEE_ACCESS_TOKEN=$(APIGEE_ACCESS_TOKEN)
+
+          echo "SERVICE_ARTIFACT_NAME: ${SERVICE_ARTIFACT_NAME}"
+          echo "SERVICE_BASE_PATH: ${SERVICE_BASE_PATH}"
+          echo "APIGEE_ENVIRONMENT: ${APIGEE_ENVIRONMENT}"
+          echo "PACT_BROKER_URL: ${PACT_BROKER_URL}"
+          echo "PACT_BROKER_BASIC_AUTH_USERNAME: ${PACT_BROKER_BASIC_AUTH_USERNAME}"
+          echo "PACT_BROKER_BASIC_AUTH_PASSWORD: HIDDEN"
+          echo "PACT_BROKER_NEXT_URL: ${PACT_BROKER_NEXT_URL}"
+          echo "PACT_BROKER_NEXT_TOKEN: HIDDEN"
+          echo "PACT_VERSION: ${PACT_VERSION}"
+          echo "PACT_PROVIDER_URL: ${PACT_PROVIDER_URL}"
+          echo "PACT_CONSUMER: ${PACT_CONSUMER}"
+          echo "PACT_PROVIDER: ${PACT_PROVIDER}"
+          echo "SIGNING_PRIVATE_KEY_PATH: ${SIGNING_PRIVATE_KEY_PATH}"
+          echo "SIGNING_CERT_PATH: ${SIGNING_CERT_PATH}"
+          echo "API_CLIENT_ID: HIDDEN"
+          echo "API_CLIENT_SECRET: HIDDEN"
+          echo "APIGEE_ACCESS_TOKEN: HIDDEN"
+        displayName: Show PACT variables
+        variables:
+          PACT_VERSION: $[ dependencies.setPactVariables.outputs['PACT_VERSION'] ]
+          PACT_PROVIDER_URL: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER_URL'] ]
+          PACT_CONSUMER: $[ dependencies.setPactVariables.outputs['PACT_CONSUMER'] ]
+          PACT_PROVIDER: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER'] ]
+          SIGNING_PRIVATE_KEY_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_PRIVATE_KEY_PATH'] ]
+          SIGNING_CERT_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_CERT_PATH'] ]
+          API_CLIENT_ID: $[ dependencies.setPactVariables.outputs['API_CLIENT_ID'] ]
+          API_CLIENT_SECRET: $[ dependencies.setPactVariables.outputs['API_CLIENT_SECRET'] ]
+          APIGEE_ACCESS_TOKEN: $[ dependencies.setPactVariables.outputs['APIGEE_ACCESS_TOKEN'] ]
+        dependsOn: setPactVariables
+        name: showPactVariables
+      - bash: |
+          #!/bin/bash
+
+          set -euo pipefail
+
+          cd $(Pipeline.Workspace)/s/
+
+          export SERVICE_ARTIFACT_NAME=$(SERVICE_ARTIFACT_NAME)
+          export SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
+          export APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
+          export PACT_BROKER_URL=$(PACT_BROKER_URL)
+          export PACT_BROKER_BASIC_AUTH_USERNAME=$(PACT_BROKER_BASIC_AUTH_USERNAME)
+          export PACT_BROKER_BASIC_AUTH_PASSWORD=$(PACT_BROKER_BASIC_AUTH_PASSWORD)
+          export PACT_BROKER_NEXT_URL=$(PACT_BROKER_NEXT_URL)
+          export PACT_BROKER_NEXT_TOKEN=$(PACT_BROKER_NEXT_TOKEN)
+          export PACT_VERSION=$(PACT_VERSION)
+          export PACT_PROVIDER_URL=$(PACT_PROVIDER_URL)
+          export PACT_CONSUMER=$(PACT_CONSUMER)
+          export PACT_PROVIDER=$(PACT_PROVIDER)
+          export SIGNING_PRIVATE_KEY_PATH=$(SIGNING_PRIVATE_KEY_PATH)
+          export SIGNING_CERT_PATH=$(SIGNING_CERT_PATH)
+          export API_CLIENT_ID=$(API_CLIENT_ID)
+          export API_CLIENT_SECRET=$(API_CLIENT_SECRET)
+          export APIGEE_ACCESS_TOKEN=$(APIGEE_ACCESS_TOKEN)
+
+          # Poll deploying API until our deployed version matches the release version
+          if [ "$APIGEE_ENVIRONMENT" != "prod" ]; then
+              envPrefix="$APIGEE_ENVIRONMENT."
+          fi;
+          url="https://${envPrefix}api.service.nhs.uk/$SERVICE_BASE_PATH/_status"
+          interval_in_seconds=5
+          releaseCommit="$(Build.SourceVersion)"
+          printf "\nPolling %s every %s seconds, until commit is: %s\n" "$url" "$interval_in_seconds" "$releaseCommit"
+          attempts=0
+          success=0
+          until [ $attempts -eq 60 ]
+          do
+          echo "attempt: ${attempts}"
+          responseData=$(curl -H "apiKey: $(status-endpoint-api-key)" "$url" -s)
+          deployedCommit=$(echo "$responseData" | jq -r ".commitId" || echo "not_found")
+          dependenciesUp=$(echo "$responseData" | jq -r ".status" || echo "not_found")
+          if [ "$deployedCommit" == "$releaseCommit" ] && [ "$dependenciesUp" == "pass" ]; then
+              success=1
+              break;
+          fi;
+          ((attempts=attempts+1))
+          echo "sleeping ${interval_in_seconds} seconds"
+          sleep $interval_in_seconds;
+          done
+
+          if [ $success == 0 ]
+          then
+              echo "Smoke tests failed, API was not ready in time"
+              exit 255
+          fi
+        displayName: Wait for API deploy
+        condition: and(succeeded(), eq(variables['run_smoke_tests'], 'true'))
+        variables:
+          PACT_VERSION: $[ dependencies.setPactVariables.outputs['PACT_VERSION'] ]
+          PACT_PROVIDER_URL: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER_URL'] ]
+          PACT_CONSUMER: $[ dependencies.setPactVariables.outputs['PACT_CONSUMER'] ]
+          PACT_PROVIDER: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER'] ]
+          SIGNING_PRIVATE_KEY_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_PRIVATE_KEY_PATH'] ]
+          SIGNING_CERT_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_CERT_PATH'] ]
+          API_CLIENT_ID: $[ dependencies.setPactVariables.outputs['API_CLIENT_ID'] ]
+          API_CLIENT_SECRET: $[ dependencies.setPactVariables.outputs['API_CLIENT_SECRET'] ]
+          APIGEE_ACCESS_TOKEN: $[ dependencies.setPactVariables.outputs['APIGEE_ACCESS_TOKEN'] ]
+        dependsOn: setPactVariables
+      - bash: |
+          #!/bin/bash
+
+          set -euo pipefail
+
+          export SERVICE_ARTIFACT_NAME=$(SERVICE_ARTIFACT_NAME)
+          export SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
+          export APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
+          export PACT_BROKER_URL=$(PACT_BROKER_URL)
+          export PACT_BROKER_BASIC_AUTH_USERNAME=$(PACT_BROKER_BASIC_AUTH_USERNAME)
+          export PACT_BROKER_BASIC_AUTH_PASSWORD=$(PACT_BROKER_BASIC_AUTH_PASSWORD)
+          export PACT_BROKER_NEXT_URL=$(PACT_BROKER_NEXT_URL)
+          export PACT_BROKER_NEXT_TOKEN=$(PACT_BROKER_NEXT_TOKEN)
+          export PACT_VERSION=$(PACT_VERSION)
+          export PACT_PROVIDER_URL=$(PACT_PROVIDER_URL)
+          export PACT_CONSUMER=$(PACT_CONSUMER)
+          export PACT_PROVIDER=$(PACT_PROVIDER)
+          export SIGNING_PRIVATE_KEY_PATH=$(SIGNING_PRIVATE_KEY_PATH)
+          export SIGNING_CERT_PATH=$(SIGNING_CERT_PATH)
+          export API_CLIENT_ID=$(API_CLIENT_ID)
+          export API_CLIENT_SECRET=$(API_CLIENT_SECRET)
+          export APIGEE_ACCESS_TOKEN=$(APIGEE_ACCESS_TOKEN)
+
           cd $(Pipeline.Workspace)/s/$SERVICE_NAME/$SERVICE_ARTIFACT_NAME
 
           # Publish
@@ -208,10 +303,40 @@ extends:
           make publish-pacts > /dev/null
         displayName: Create PACT tests and publish
         condition: and(succeeded(), eq(variables['run_smoke_tests'], 'true'))
+        variables:
+          PACT_VERSION: $[ dependencies.setPactVariables.outputs['PACT_VERSION'] ]
+          PACT_PROVIDER_URL: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER_URL'] ]
+          PACT_CONSUMER: $[ dependencies.setPactVariables.outputs['PACT_CONSUMER'] ]
+          PACT_PROVIDER: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER'] ]
+          SIGNING_PRIVATE_KEY_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_PRIVATE_KEY_PATH'] ]
+          SIGNING_CERT_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_CERT_PATH'] ]
+          API_CLIENT_ID: $[ dependencies.setPactVariables.outputs['API_CLIENT_ID'] ]
+          API_CLIENT_SECRET: $[ dependencies.setPactVariables.outputs['API_CLIENT_SECRET'] ]
+          APIGEE_ACCESS_TOKEN: $[ dependencies.setPactVariables.outputs['APIGEE_ACCESS_TOKEN'] ]
+        dependsOn: setPactVariables
       - bash: |
           #!/bin/bash
 
           set -euo pipefail
+
+          export SERVICE_ARTIFACT_NAME=$(SERVICE_ARTIFACT_NAME)
+          export SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
+          export APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
+          export PACT_BROKER_URL=$(PACT_BROKER_URL)
+          export PACT_BROKER_BASIC_AUTH_USERNAME=$(PACT_BROKER_BASIC_AUTH_USERNAME)
+          export PACT_BROKER_BASIC_AUTH_PASSWORD=$(PACT_BROKER_BASIC_AUTH_PASSWORD)
+          export PACT_BROKER_NEXT_URL=$(PACT_BROKER_NEXT_URL)
+          export PACT_BROKER_NEXT_TOKEN=$(PACT_BROKER_NEXT_TOKEN)
+          export PACT_VERSION=$(PACT_VERSION)
+          export PACT_PROVIDER_URL=$(PACT_PROVIDER_URL)
+          export PACT_CONSUMER=$(PACT_CONSUMER)
+          export PACT_PROVIDER=$(PACT_PROVIDER)
+          export SIGNING_PRIVATE_KEY_PATH=$(SIGNING_PRIVATE_KEY_PATH)
+          export SIGNING_CERT_PATH=$(SIGNING_CERT_PATH)
+          export API_CLIENT_ID=$(API_CLIENT_ID)
+          export API_CLIENT_SECRET=$(API_CLIENT_SECRET)
+          export APIGEE_ACCESS_TOKEN=$(APIGEE_ACCESS_TOKEN)
+
           cd $(Pipeline.Workspace)/s/$SERVICE_NAME/$SERVICE_ARTIFACT_NAME
 
           # Verify
@@ -219,10 +344,39 @@ extends:
           make verify-pacts
         displayName: Run smoke tests
         condition: and(succeeded(), eq(variables['run_smoke_tests'], 'true'))
+        variables:
+          PACT_VERSION: $[ dependencies.setPactVariables.outputs['PACT_VERSION'] ]
+          PACT_PROVIDER_URL: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER_URL'] ]
+          PACT_CONSUMER: $[ dependencies.setPactVariables.outputs['PACT_CONSUMER'] ]
+          PACT_PROVIDER: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER'] ]
+          SIGNING_PRIVATE_KEY_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_PRIVATE_KEY_PATH'] ]
+          SIGNING_CERT_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_CERT_PATH'] ]
+          API_CLIENT_ID: $[ dependencies.setPactVariables.outputs['API_CLIENT_ID'] ]
+          API_CLIENT_SECRET: $[ dependencies.setPactVariables.outputs['API_CLIENT_SECRET'] ]
+          APIGEE_ACCESS_TOKEN: $[ dependencies.setPactVariables.outputs['APIGEE_ACCESS_TOKEN'] ]
+        dependsOn: setPactVariables
       - bash: |
           #!/bin/bash
 
           set -euo pipefail
+
+          export SERVICE_ARTIFACT_NAME=$(SERVICE_ARTIFACT_NAME)
+          export SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
+          export APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
+          export PACT_BROKER_URL=$(PACT_BROKER_URL)
+          export PACT_BROKER_BASIC_AUTH_USERNAME=$(PACT_BROKER_BASIC_AUTH_USERNAME)
+          export PACT_BROKER_BASIC_AUTH_PASSWORD=$(PACT_BROKER_BASIC_AUTH_PASSWORD)
+          export PACT_BROKER_NEXT_URL=$(PACT_BROKER_NEXT_URL)
+          export PACT_BROKER_NEXT_TOKEN=$(PACT_BROKER_NEXT_TOKEN)
+          export PACT_VERSION=$(PACT_VERSION)
+          export PACT_PROVIDER_URL=$(PACT_PROVIDER_URL)
+          export PACT_CONSUMER=$(PACT_CONSUMER)
+          export PACT_PROVIDER=$(PACT_PROVIDER)
+          export SIGNING_PRIVATE_KEY_PATH=$(SIGNING_PRIVATE_KEY_PATH)
+          export SIGNING_CERT_PATH=$(SIGNING_CERT_PATH)
+          export API_CLIENT_ID=$(API_CLIENT_ID)
+          export API_CLIENT_SECRET=$(API_CLIENT_SECRET)
+          export APIGEE_ACCESS_TOKEN=$(APIGEE_ACCESS_TOKEN)
 
           # Cleanup for PRs
           if [[ $SERVICE_ARTIFACT_NAME != v* ]]
@@ -231,6 +385,17 @@ extends:
           fi
         displayName: Cleanup PACT tests
         condition: and(succeeded(), eq(variables['run_smoke_tests'], 'true'))
+        variables:
+          PACT_VERSION: $[ dependencies.setPactVariables.outputs['PACT_VERSION'] ]
+          PACT_PROVIDER_URL: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER_URL'] ]
+          PACT_CONSUMER: $[ dependencies.setPactVariables.outputs['PACT_CONSUMER'] ]
+          PACT_PROVIDER: $[ dependencies.setPactVariables.outputs['PACT_PROVIDER'] ]
+          SIGNING_PRIVATE_KEY_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_PRIVATE_KEY_PATH'] ]
+          SIGNING_CERT_PATH: $[ dependencies.setPactVariables.outputs['SIGNING_CERT_PATH'] ]
+          API_CLIENT_ID: $[ dependencies.setPactVariables.outputs['API_CLIENT_ID'] ]
+          API_CLIENT_SECRET: $[ dependencies.setPactVariables.outputs['API_CLIENT_SECRET'] ]
+          APIGEE_ACCESS_TOKEN: $[ dependencies.setPactVariables.outputs['APIGEE_ACCESS_TOKEN'] ]
+        dependsOn: setPactVariables
       - task: PublishBuildArtifacts@1
         displayName: "Publish Test Prescriptions"
         inputs:
