Add condition to wait for EPS deploy and run smoke tests in internal-dev only

diff --git a/tool/azure/azure-release-template.yml b/tool/azure/azure-release-template.yml
--- a/tool/azure/azure-release-template.yml
+++ b/tool/azure/azure-release-template.yml
@@ -18,6 +18,14 @@ extends:
     prod_requires_approval: true
     post_deploy:
       - bash: |
+          if [ "$(APIGEE_ENVIRONMENT)" == "internal-dev" ]
+          then
+            echo "##vso[task.setvariable variable=is_internal_dev]true"
+          else
+            echo "##vso[task.setvariable variable=is_internal_dev]false"
+          fi
+        displayName: Check is internal-dev
+      - bash: |
           #!/bin/bash
 
           set -euo pipefail
@@ -25,13 +33,12 @@ extends:
           export SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
           export APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
 
-          # Poll EPS API until our deployed version of EPS matches the release version
+          # Poll API until our deployed version matches the release version
           if [ "$APIGEE_ENVIRONMENT" != "prod" ]; then
               envPrefix="$APIGEE_ENVIRONMENT."
           fi;
-          basePath="${SERVICE_BASE_PATH/eps-api-tool/electronic-prescriptions}"
-          url="https://${envPrefix}api.service.nhs.uk/$basePath/_status"
-          interval_in_seconds=10
+          url="https://${envPrefix}api.service.nhs.uk/$SERVICE_BASE_PATH/_status"
+          interval_in_seconds=5
           releaseCommit="$(Build.SourceVersion)"
           printf "\nPolling %s every %s seconds, until commit is: %s\n" "$url" "$interval_in_seconds" "$releaseCommit"
           attempts=0
@@ -54,7 +61,7 @@ extends:
               echo "Smoke tests failed, API was not ready in time"
               exit 255
           fi
-        displayName: Wait for EPS deploy
+        displayName: Wait for deploy
       - bash: |
           #!/bin/bash
 
@@ -63,9 +70,45 @@ extends:
           export SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
           export APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
 
-          if [ "$APIGEE_ENVIRONMENT" == "internal-dev" ]; then
-            cd "$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e-tests"
-            npm ci
-            npm t
+          # Poll EPS API until our deployed version of EPS matches the release version
+          if [ "$APIGEE_ENVIRONMENT" != "prod" ]; then
+              envPrefix="$APIGEE_ENVIRONMENT."
           fi;
-        displayName: Run selenium tests
+          basePath="${SERVICE_BASE_PATH/eps-api-tool/electronic-prescriptions}"
+          url="https://${envPrefix}api.service.nhs.uk/$basePath/_status"
+          interval_in_seconds=60
+          interval_in_minutes=interval_in_seconds/60
+          releaseCommit="$(Build.SourceVersion)"
+          printf "\nPolling %s every %s mintues, until commit is: %s\n" "$url" "$interval_in_minutes" "$releaseCommit"
+          attempts=0
+          success=0
+          until [ $attempts -eq 6 ]
+          do
+          responseData=$(curl -H "apiKey: $(status-endpoint-api-key)" "$url" -s)
+          deployedCommit=$(echo "$responseData" | jq -r ".commitId")
+          dependenciesUp=$(echo "$responseData" | jq -r ".status")
+          if [ "$deployedCommit" == "$releaseCommit" ] && [ "$dependenciesUp" == "pass" ]; then
+              success=1
+              break;
+          fi;
+          ((attempts=attempts+1))
+          sleep $interval_in_seconds;
+          done
+
+          if [ $success == 0 ]
+          then
+              echo "Smoke tests failed, API was not ready in time"
+              exit 255
+          fi
+        condition: and(succeeded(), eq(variables['is_internal_dev'], 'true'))
+        displayName: Wait for EPS deploy
+      - bash: |
+          #!/bin/bash
+
+          set -euo pipefail
+
+          cd "$(SERVICE_NAME)/$(SERVICE_ARTIFACT_NAME)/e2e-tests"
+          npm ci
+          npm t
+        condition: and(succeeded(), eq(variables['is_internal_dev'], 'true'))
+        displayName: Run smoke tests
