Add wait for eps deploy hook before any eps-api-tool tests

diff --git a/tool/azure/azure-pr-pipeline.yml b/tool/azure/azure-pr-pipeline.yml
--- a/tool/azure/azure-pr-pipeline.yml
+++ b/tool/azure/azure-pr-pipeline.yml
@@ -38,3 +38,42 @@ extends:
     apigee_deployments:
       - environment: internal-dev
         make_spec_visible: false
+    post_deploy:
+      - bash: |
+          #!/bin/bash
+
+          set -euo pipefail
+
+          SERVICE_BASE_PATH=$(SERVICE_BASE_PATH)
+          export SERVICE_BASE_PATH="${SERVICE_BASE_PATH/eps-api-tool/"electronic-prescriptions"}"
+          export APIGEE_ENVIRONMENT=$(APIGEE_ENVIRONMENT)
+
+          # Poll EPS API until our deployed version matches the release version
+          if [ "$APIGEE_ENVIRONMENT" != "prod" ]; then
+              envPrefix="$APIGEE_ENVIRONMENT."
+          fi;
+          url="https://${envPrefix}api.service.nhs.uk/$SERVICE_BASE_PATH/_status"
+          interval_in_seconds=5
+          releaseCommit="$(Build.SourceVersion)"
+          printf "\nPolling %s every %s seconds, until commit is: %s\n" "$url" "$interval_in_seconds" "$releaseCommit"
+          attempts=0
+          success=0
+          until [ $attempts -eq 60 ]
+          do
+          responseData=$(curl -H "apiKey: $(status-endpoint-api-key)" "$url" -s)
+          deployedCommit=$(echo "$responseData" | jq -r ".commitId")
+          dependenciesUp=$(echo "$responseData" | jq -r ".status")
+          if [ "$deployedCommit" == "$releaseCommit" ] && [ "$dependenciesUp" == "pass" ]; then
+              success=1
+              break;
+          fi;
+          ((attempts=attempts+1))
+          sleep $interval_in_seconds;
+          done
+
+          if [ $success == 0 ]
+          then
+              echo "Failed to verify if EPS API has been succesfully deployed: API was not ready in time"
+              exit 255
+          fi
+        displayName: Wait for EPS deploy
